[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/killswitch"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/callback"
  to = "/.netlify/functions/auth"
  status = 200

[dev]
  framework = "#static"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["fs", "path"]
