[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm run build"

# Headers to improve security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://discord.com; img-src 'self' https: data:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"

# API and function redirects
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Asset redirects
[[redirects]]
  from = "/images/*"
  to = "/images/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200
  force = true

# SPA redirects
[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard.html"
  status = 200
  force = true

# Fallback redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"
  targetPort = 8888
  port = 3000
  publish = "public"
  autoLaunch = true

# Build settings
[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"

# Plugin configurations
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[functions]
  node_bundler = "esbuild"